import numpy as np
a=np.array([24,23,25])
print(a)
print(dir(np))

a=np.array([24,23,25],np.int8)
print((a)-96)
a=np.array([-32768,32767],np.int16)
print((a)-96)
f=np.array([1,2,3,4,5,6,7])
v=np.array([9,8,7,6,5,4,3])
print('f:',f)
print('v:',v)
print("type of f:",f.dtype)
print("type of v:",v.dtype)
print("dimension of f:",np.ndim(f))
print("dimension of v:",np.ndim(v))
f=np.array([1,2,3,4,5,6,7])
v=np.array((9.3,3.4,4.5,6.7))
print('f:',f)
print('v:',v)
print("type of f:",f.dtype)
print("type of v:",v.dtype)
print("dimension of f:",np.ndim(f))
print("dimension of v:",np.ndim(v))
#using two dimensional array
b=np.array([[1,2,3],
           [4,5,6]])
print(b)
print(b.dtype)
print(b.shape)
print(b[0,0],b[0,2],b[1,1])
b[0,0]=10
b[1,1]=20
print(b)
#creating array in different formats
a=np.zeros([2,2])
print(a)
a=np.zeros([3,2])
print(a)
a=np.ones([2,2])
print(a)
a=np.full([2,2])
print(a)
a=np.eye([2,2])
print(a)
a=np.random.random([2,2])
print(a)
a=np.random.randn([2,2])
print(a)
a=np.random.randint([2,2])
print(a)
a=np.random.uniform([2,2])
print(a)
#using add&sub&mul&div
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.sub(x,y))
print(x*y)
print(np.mul(x,y))
print(x/y)
print(np.div(x,y))
print(np.sqr(x))




